// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Application metadata returned by [`system_info`].
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `name` | `string` | Application name from `Cargo.toml` |
 * | `version` | `string` | Semantic version (e.g., `"0.1.0"`) |
 * | `tauri_version` | `string` | Tauri runtime version |
 * | `debug` | `boolean` | `true` in debug builds |
 */
export type AppInfo = { 
/**
 * Application name (from Cargo.toml).
 */
name: string, 
/**
 * Semantic version.
 */
version: string, 
/**
 * Rust toolchain / Tauri runtime info.
 */
tauri_version: string, 
/**
 * Whether the application is running in debug mode.
 */
debug: boolean, };
