// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single history message in a conversation.
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `role` | `string` | `"user"` or `"assistant"` |
 * | `content` | `string` | Message text content |
 * | `timestamp` | `string \| null` | ISO 8601 timestamp (omitted if absent) |
 */
export type HistoryMessage = { 
/**
 * Message role: `"user"` or `"assistant"`.
 */
role: string, 
/**
 * Message text content.
 */
content: string, 
/**
 * Optional ISO 8601 timestamp.
 */
timestamp: string | null, };
