// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for the `agent:stream:start` event.
 *
 * Emitted once when the agent begins processing a user message.
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `session_id` | `string` | The session being processed |
 * | `message_id` | `string` | Unique ID for this message turn |
 */
export type AgentStreamStart = { 
/**
 * The session being processed.
 */
session_id: string, 
/**
 * Unique ID for this message turn (used for correlation).
 */
message_id: string, };
