// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for the `agent:stream:chunk` event.
 *
 * Emitted for each text fragment generated by the agent's LLM response.
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `session_id` | `string` | The session this chunk belongs to |
 * | `message_id` | `string` | The message turn this chunk belongs to |
 * | `content` | `string` | The text fragment |
 */
export type AgentStreamChunk = {
  /**
   * The session this chunk belongs to.
   */
  session_id: string;
  /**
   * The message turn this chunk belongs to.
   */
  message_id: string;
  /**
   * The text fragment generated by the LLM.
   */
  content: string;
  /**
   * Chunk type: "text" (conversational), "tool_start" (tool begins), "tool_end" (tool completes),
   * "tool_result" (tool execution result).
   */
  chunk_type: string;
};
