// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for the `agent:stream:error` event.
 *
 * Emitted when the agent encounters a failure during processing.
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `session_id` | `string` | The session that failed |
 * | `message_id` | `string` | The message turn that failed |
 * | `code` | `string` | Machine-readable error code |
 * | `message` | `string` | Human-readable error description |
 */
export type AgentStreamError = { 
/**
 * The session that failed.
 */
session_id: string, 
/**
 * The message turn that failed.
 */
message_id: string, 
/**
 * Machine-readable error code (e.g., `"MODEL_ERROR"`).
 */
code: string, 
/**
 * Human-readable error description.
 */
message: string, };
