// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for the `agent:stream:end` event.
 *
 * Emitted once when the agent finishes successfully.
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `session_id` | `string` | The session that completed |
 * | `message_id` | `string` | The message turn that completed |
 * | `total_chunks` | `number` | Total number of chunks emitted |
 */
export type AgentStreamEnd = {
  /**
   * The session that completed.
   */
  session_id: string;
  /**
   * The message turn that completed.
   */
  message_id: string;
  /**
   * Total number of chunks emitted during this turn.
   */
  total_chunks: number;
};
