// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for writing or updating character configuration.
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `character_data` | `CharacterData` | Nested map of section → field → value |
 */
export type CharacterPayload = { 
/**
 * The character configuration data.
 */
character_data: { [key in string]: { [key in string]: string } }, };
