// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Multi-modal message payload sent from the frontend to the agent.
 *
 * # Fields
 *
 * | Field | Type | Required | Description |
 * |-------|------|----------|-------------|
 * | `session_id` | `string` | Yes | Unique session identifier |
 * | `text` | `string \| null` | No | Text message content |
 * | `image_base64_list` | `string[]` | No | Base64-encoded image data (uploaded to backend before WS call) |
 * | `image_path_list` | `string[]` | No | HTTP image URLs already uploaded to the backend |
 *
 * At least one of `text` or `image_base64_list` should be provided.
 *
 * # Example
 *
 * ```json
 * {
 *   "session_id": "default",
 *   "text": "Hello, how are you?",
 *   "image_base64_list": [],
 *   "image_path_list": []
 * }
 * ```
 */
export type ChatRequest = { 
/**
 * Unique session identifier.
 */
session_id: string, 
/**
 * Optional text message content.
 */
text: string | null, 
/**
 * Optional list of base64-encoded images for multi-modal input.
 */
image_base64_list: Array<string>, 
/**
 * Optional list of HTTP image URLs already uploaded to the backend.
 */
image_path_list: Array<string>, };
