// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single streaming chunk returned by the agent.
 *
 * The frontend receives a `Vec<ChatChunk>` (or individual chunks
 * via Tauri events for true streaming).
 *
 * # Fields
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `content` | `string` | Text fragment for this chunk |
 * | `done` | `boolean` | `true` if this is the final chunk |
 */
export type ChatChunk = { 
/**
 * The text fragment for this chunk.
 */
content: string, 
/**
 * Whether this is the final chunk.
 */
done: boolean, };
