// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to clear a session's state.
 *
 * | Field | Type | Required | Description |
 * |-------|------|----------|-------------|
 * | `session_id` | `string` | Yes | Session to clear |
 */
export type ClearSessionRequest = {
  /**
   * The session ID to clear.
   */
  session_id: string;
};
