// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSON-serializable error sent to the frontend via Tauri IPC.
 *
 * Designed to be both human-readable and machine-parseable:
 *
 * ```json
 * {
 *   "code": "MODEL_ERROR",
 *   "message": "connection refused: http://localhost:11434"
 * }
 * ```
 */
export type FrontendError = {
  /**
   * Stable error code (e.g. `"MODEL_ERROR"`).
   */
  code: string;
  /**
   * Human-readable description.
   */
  message: string;
};
