// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health-check response from [`system_health`].
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `healthy` | `boolean` | `true` if all subsystems are operational |
 * | `message` | `string` | Human-readable status description |
 */
export type HealthStatus = { 
/**
 * Whether all core subsystems are operational.
 */
healthy: boolean, 
/**
 * Human-readable status description.
 */
message: string, };
