// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response after reading all system prompt files.
 *
 * | Field | Type | Description |
 * |-------|------|-------------|
 * | `file_to_content` | `Record<string, string>` | Map of filename to file content |
 */
export type PromptFileResponse = {
  /**
   * Map of filename (e.g., `"AGENTS.md"`) to file content.
   */
  file_to_content: { [key in string]: string };
};
