// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to stop an ongoing agent generation.
 *
 * | Field | Type | Required | Description |
 * |-------|------|----------|-------------|
 * | `session_id` | `string` | Yes | Session to stop |
 */
export type StopRequest = { 
/**
 * The session whose generation should be cancelled.
 */
session_id: string, };
