"""Registry sub-package: storage, queries, and state management for sub-agent run records."""

from .memory import (
    get as get_run,
    set_run,
    delete as delete_run,
    update as update_run,
    snapshot,
    values as all_runs,
    size,
    clear,
    find_by_child_session_key,
)
from .queries import (
    list_runs_for_requester,
    list_descendant_runs,
    count_active_runs_for_session,
    count_active_descendant_runs,
    count_pending_descendant_runs,
    get_run_by_child_session_key,
    build_read_index,
    find_run_by_task_name,
)
from .run_manager import (
    register_run,
    mark_run_paused_after_yield,
    mark_run_running,
    complete_run,
    replace_run_after_steer,
    remove_run,
    update_run as manager_update_run,
    save_kill_reconciliation,
    clear_kill_reconciliation,
)
from .delivery_state import (
    ensure_delivery_state,
    is_delivery_pending,
    is_delivery_delivered,
    is_delivery_failed,
    is_delivery_suspended,
    is_delivery_terminal,
    should_retry_delivery,
    is_delivery_expired,
    should_discard_delivery,
    mark_delivery_pending,
    mark_delivery_in_progress,
    mark_delivery_delivered,
    mark_delivery_failed,
    mark_delivery_suspended,
    mark_delivery_discarded,
)
from .state import init_registry, persist_runs_to_disk, restore_runs_from_disk
from .helpers import (
    cap_frozen_result_text,
    resolve_announce_retry_delay_seconds,
    is_live_unended_run,
    has_run_ended,
    is_stale_unended_run,
    should_keep_child_link,
    reconcile_orphaned_run,
)
from .completion import (
    should_update_run_outcome,
    resolve_finalized_task_state,
    resolve_lifecycle_outcome,
    emit_ended_hook_once,
)
from .cleanup import resolve_cleanup_completion_reason, resolve_deferred_cleanup_decision, should_cleanup_run
from .task_refs import register_task, get_task, remove_task, cancel_task
from .yield_events import (
    register_yield_event,
    get_yield_event,
    remove_yield_event,
    wake_yield,
    wake_yield_if_all_children_settled,
)
from .read import (
    get_run_readonly,
    list_runs_for_requester_readonly,
    list_runs_for_controller_readonly,
    list_descendant_runs_readonly,
    count_active_runs_readonly,
    count_active_descendant_runs_readonly,
    get_run_by_child_session_key_readonly,
    get_snapshot_readonly,
    build_read_index_readonly,
)
from .reconciliation import (
    resolve_run_orphan_reason,
    resolve_completion_from_session,
    resolve_completion_from_session_entry,
    SubagentSessionCompletion,
)
from .generation import (
    next_subagent_run_generation,
    is_superseded_run,
    get_latest_run_by_child_session_key,
)
from .sweeper import start_sweeper, stop_sweeper
from .lifecycle import (
    complete_subagent_run,
    resume_subagent_run,
    finalize_suspended_deliveries,
    finalize_failed_deliveries,
    recover_orphaned_runs,
    pressure_prune_suspended_deliveries,
)
from .terminal_gen import TerminalGenerationTracker, get_terminal_gen_tracker
from .settle_wake import SettleWakeState, RequesterSettleWakeBatch, get_settle_wake_batch
from .work_admission import is_gateway_draining, set_draining, run_with_work_admission, pending_root_work_count

__all__ = [
    "get_run",
    "set_run",
    "delete_run",
    "update_run",
    "snapshot",
    "all_runs",
    "size",
    "clear",
    "find_by_child_session_key",
    "list_runs_for_requester",
    "list_descendant_runs",
    "count_active_runs_for_session",
    "count_active_descendant_runs",
    "count_pending_descendant_runs",
    "get_run_by_child_session_key",
    "build_read_index",
    "find_run_by_task_name",
    "register_run",
    "mark_run_paused_after_yield",
    "mark_run_running",
    "complete_run",
    "replace_run_after_steer",
    "remove_run",
    "manager_update_run",
    "init_registry",
    "persist_runs_to_disk",
    "restore_runs_from_disk",
    "is_delivery_pending",
    "is_delivery_delivered",
    "is_delivery_failed",
    "is_delivery_suspended",
    "is_delivery_terminal",
    "should_retry_delivery",
    "is_delivery_expired",
    "should_discard_delivery",
    "mark_delivery_pending",
    "mark_delivery_in_progress",
    "mark_delivery_delivered",
    "mark_delivery_failed",
    "mark_delivery_suspended",
    "mark_delivery_discarded",
    "cap_frozen_result_text",
    "resolve_announce_retry_delay_seconds",
    "is_live_unended_run",
    "has_run_ended",
    "is_stale_unended_run",
    "should_keep_child_link",
    "reconcile_orphaned_run",
    "resolve_finalized_task_state",
    "resolve_lifecycle_outcome",
    "emit_ended_hook_once",
    "resolve_cleanup_completion_reason",
    "resolve_deferred_cleanup_decision",
    "should_cleanup_run",
    "register_task",
    "get_task",
    "remove_task",
    "cancel_task",
    "register_yield_event",
    "get_yield_event",
    "remove_yield_event",
    "wake_yield",
    "wake_yield_if_all_children_settled",
    "get_run_readonly",
    "list_runs_for_requester_readonly",
    "list_runs_for_controller_readonly",
    "list_descendant_runs_readonly",
    "count_active_runs_readonly",
    "count_active_descendant_runs_readonly",
    "get_run_by_child_session_key_readonly",
    "get_snapshot_readonly",
    "build_read_index_readonly",
    "SubagentSessionCompletion",
    "save_kill_reconciliation",
    "clear_kill_reconciliation",
    "next_subagent_run_generation",
    "is_superseded_run",
    "get_latest_run_by_child_session_key",
    "start_sweeper",
    "stop_sweeper",
    "complete_subagent_run",
    "resume_subagent_run",
    "finalize_suspended_deliveries",
    "finalize_failed_deliveries",
    "recover_orphaned_runs",
    "pressure_prune_suspended_deliveries",
    "TerminalGenerationTracker",
    "get_terminal_gen_tracker",
    "SettleWakeState",
    "RequesterSettleWakeBatch",
    "get_settle_wake_batch",
    "is_gateway_draining",
    "set_draining",
    "run_with_work_admission",
    "pending_root_work_count",
]
