import time
import asyncio
from pathlib import Path
from loguru import logger
from bus import MessageBus
from runtime import Register
from .type import SubAgentOutput
from type.bus import InboundMessage
from threading import Thread, Event
from skills.loader import get_skills_text
from config import TEMP_DIR, WORKSPACE_DIR
from typing import Any, Callable, Awaitable
from workspace import CORE_SYSTEM_FILE_NAMES
from models.LLMs.main_llm import build_main_llm
from langgraph.graph.state import CompiledStateGraph

from workspace.prompt_builder import build_system_prompt
from pub_func import render_template_file, build_agent_config
from .commander import build_commander
from agent.middlewares.heartbeat_staleness import HeartbeatTimeoutError
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage


_current_dir = Path(__file__).parent
_template_dir = (_current_dir / "templates").resolve()

class SubagentManager:
    """Manages background subagent execution with a dedicated thread + event loop."""

    """Singleton pattern"""
    _instance = None
    _initialized = False

    def __new__(cls, *args, **kwargs):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(
        self,
        bus: MessageBus | None = None,
    ):
        if SubagentManager._initialized:
            return

        if bus is None:
            bus = MessageBus()
        self._bus = bus
        self._running_tasks: dict[str, asyncio.Task[None]] = {}
        self._session_tasks: dict[str, set[str]] = {}  # session_id -> {task_id, ...}
        self._consumer: Callable[[InboundMessage], Awaitable[None]] | None = None

        # Create a dedicated event loop + daemon thread, isolated from the main thread
        self._event_loop: asyncio.AbstractEventLoop = asyncio.new_event_loop()
        self._loop_thread: Thread = Thread(target=self._run_loop, daemon=True, name="subagent-loop")
        self._loop_ready = Event()
        self._loop_thread.start()
        self._loop_ready.wait()  # block until loop is set up and running

        SubagentManager._initialized = True


    def _run_loop(self) -> None:
        """Dedicated thread entry: set event loop and run forever."""
        asyncio.set_event_loop(self._event_loop)
        self._loop_ready.set()
        try:
            self._event_loop.run_forever()
        except Exception:
            pass

    async def spawn(
        self,
        session_id: str,
        task: str,
        label: str | None = None,
    ) -> str:
        """Spawn a subagent to execute a task in the background."""
        task_id = str(int(time.time() * 1000))
        display_label = label or task[:30] + ("..." if len(task) > 30 else "")

        bg_task = self._event_loop.create_task(
            self._run_subagent(
                session_id= session_id,
                task_id= task_id,
                task= task,
                label= display_label
            )
        )

        self._running_tasks[task_id] = bg_task
        self._session_tasks.setdefault(session_id, set()).add(task_id)

        def _cleanup(_: asyncio.Task) -> None:
            self._running_tasks.pop(task_id, None)
            if ids := self._session_tasks.get(session_id):
                ids.discard(task_id)
                if not ids:
                    del self._session_tasks[session_id]

        bg_task.add_done_callback(_cleanup)

        logger.info("Spawned subagent [{}]: {}", task_id, display_label)
        return f"Subagent [{display_label}] started (id: {task_id}). I'll notify you when it completes."

    def get_event_loop(self) -> asyncio.AbstractEventLoop:
        """Get the event loop."""
        return self._event_loop

    def get_buts(self)-> MessageBus:
        return self._bus

    @staticmethod
    def _build_subagent_prompt() -> str:
        """
        Build the subagent prompt.

        Returns:
            The subagent prompt string
        """

        skill_guide_text: str = f"""
        Additional notes:
        1. Replace <skill_folder> with the directory containing the SKILL.md file. For example, if the skill file is at "./skills/text_to_image/SKILL.md", the directory would be "./skills/text_to_image"
        2. Temporary resources generated by skills (e.g., images, audio) are stored in {TEMP_DIR.as_posix()}
        """
        skill_paths:str = get_skills_text(selected_skill_names = None, exclude_auth_skills=True) # Exclude high-permission skills
        skill_paths = f"{skill_paths}\n\n{skill_guide_text}"

        file_paths: list[str] = []

        # Ensure core files are always included
        for core_file in CORE_SYSTEM_FILE_NAMES:
            path = WORKSPACE_DIR / core_file
            if not path.exists():
                continue
            file_paths.append(path.read_text(encoding="utf-8"))

        parts = [skill_paths, *file_paths]

        return "\n\n".join(p for p in parts if p)

    async def _run_subagent(
        self,
        session_id: str,
        task_id: str,
        task: str,
        label: str,
    ) -> None:
        """Execute the subagent task and announce the result."""
        logger.info("Subagent [{}] starting task: {}", task_id, label)

        commander_session_id: str = f"commander-{session_id}"
        try:
            logger.debug("Subagent [{}] step 1/4: building commander agent...", task_id)
            agent: CompiledStateGraph = build_commander()
            logger.debug("Subagent [{}] step 1/4: commander agent built OK", task_id)

            logger.debug("Subagent [{}] step 2/4: calling agent.ainvoke...", task_id)
            agent_res: dict[str, Any] = await agent.ainvoke(
                input={
                    "master_session_id": session_id,
                    "session_id": commander_session_id,
                    "task_id": task_id,
                    "role": "commander",
                    "messages": [HumanMessage(content=task)]
                },
                config=build_agent_config(session_id=commander_session_id)
            )
            logger.debug("Subagent [{}] step 2/4: ainvoke returned, keys={}", task_id, list(agent_res.keys()) if agent_res else "None")






            structured_response: SubAgentOutput | None = agent_res.get("structured_response")
            logger.debug("Subagent [{}] step 3/4: structured_response={}", task_id,
                f"status={structured_response.status}" if structured_response else "None")

            announce_content: str = render_template_file(
                file_path=(_template_dir / "subagent_announce.md").resolve().as_posix(),
                variables={
                    "label": label,
                    "status_text": "completed successfully" if structured_response and structured_response.status == "ok" else "failed",
                    "task": task,
                    "finish_reason": structured_response.finish_reason if structured_response else "",
                    "result": structured_response.result if structured_response else "",
                }
            )
            logger.debug("Subagent [{}] step 4/4: announce template rendered", task_id)

        except HeartbeatTimeoutError as e:
            logger.warning("Subagent [{}] heartbeat timeout: {}", task_id, e)
            announce_content: str = render_template_file(
                file_path=(_template_dir / "subagent_announce.md").resolve().as_posix(),
                variables={
                    "label": label,
                    "status_text": "heartbeat timeout",
                    "task": task,
                    "finish_reason": str(e),
                    "result": "",
                }
            )

        except Exception as e:
            logger.exception(e)
            announce_content: str = render_template_file(
                file_path=(_template_dir / "subagent_announce.md").resolve().as_posix(),
                variables={
                    "label": label,
                    "status_text": "crash error",
                    "task": task,
                    "finish_reason": str(e),
                    "result": "",
                }
            )

        finally:
            # clear all runtime register
            Register.clear_all_register_sessions(commander_session_id)

        msg = InboundMessage(
            channel="system",
            sender_id="subagent",
            chat_id="direct",
            content=announce_content,
            session_id=session_id,
            metadata={
                "injected_event": "subagent_result",
                "subagent_task_id": task_id,
            },
        )

        logger.info("Subagent [{}] completed. Result: status={}, finish_reason={}, result={}", task_id,
            structured_response.status if structured_response else "N/A",
            structured_response.finish_reason if structured_response else "N/A",
            (structured_response.result[:200] + "...") if structured_response and len(structured_response.result) > 200 else (structured_response.result if structured_response else "N/A"))

        await self._bus.publish_inbound(msg)


    async def cancel_by_session(self, session_id: str) -> int:
        """Cancel all subagents for the given session. Returns count canceled."""
        tasks = [self._running_tasks[tid] for tid in self._session_tasks.get(session_id, [])
                 if tid in self._running_tasks and not self._running_tasks[tid].done()]
        for t in tasks:
            t.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)
        return len(tasks)

    def set_consumer(self, consumer: Callable[[InboundMessage], Awaitable[None]])->None:
        self._consumer = consumer

    async def _consume_loop(self):
        # Create a fresh LLM for the consume loop on the daemon thread's event loop.
        _llm = build_main_llm()
        while True:
            try:
                msg: InboundMessage = await self._bus.consume_inbound()
            except Exception as e:
                logger.error("Subagent consume loop failed to consume from bus: {}", e)
                continue

            if self._consumer:
                try:
                    # Personalize the result to match the character persona
                    messages = [SystemMessage(
                        content=
                        build_system_prompt()
                        + '\n\nPlease convey the results to the user in a tone that matches the character persona.'
                    ), HumanMessage(content=msg.content)]

                    res_msg: AIMessage = await _llm.ainvoke(messages)
                    # Preserve the raw result alongside the personalized summary
                    msg.content = res_msg.content + '\n\n---\n' + msg.content
                except Exception as e:
                    logger.error("Subagent consume failed (LLM personalize): {}", e)
                    # Fall back to the raw result — never drop it
                finally:
                    # Always forward the result, even if personalization failed
                    try:
                        await self._consumer(msg)
                    except Exception as e:
                        logger.error("Subagent consumer callback failed: {}", e)

    def start_service(self) -> None:
        """Start the consume loop on the dedicated thread's event loop."""
        asyncio.run_coroutine_threadsafe(
            self._consume_loop(),
            self._event_loop,
        )

    def get_running_count(self) -> int:
        """Return the number of currently running subagents."""
        return len(self._running_tasks)

    def get_running_count_by_session(self, session_id: str) -> int:
        """Return the number of currently running subagents for a session."""
        tids: set[str] = self._session_tasks.get(session_id, set())
        return sum(
            1 for tid in tids
            if tid in self._running_tasks and not self._running_tasks[tid].done()
        )