import type { NitroFetchRequest } from 'nitropack';
import type { Response } from '~/types/response';
import { sendRequestErrorToast } from './toast';

interface Params {
  url: NitroFetchRequest;
  opts?: { [key: string]: any } | FormData;
  method?: 'get' | 'post' | 'put' | 'patch' | 'delete';
  contentType?: 'application/x-www-form-urlencoded' | 'application/json' | 'multipart/form-data';
  lazy?: boolean;
  headeropts?: { [key: string]: any };
  onError?: () => void;
  initialCache?: boolean;
  server?: boolean;
  watch?: [];
}

/**
 * Replace path variables
 *
 * @param { NitroFetchRequest } url Request path
 * @param { any } params Path parameters
 * @returns { NitroFetchRequest } The request path after replacement
 */
const replacePathVariables = (url: NitroFetchRequest, params: any = {}): NitroFetchRequest => {
  if (Object.keys(params).length === 0) {
    return url;
  }
  const regex = /\/:(\w+)/gm;
  let formattedURL = url as string;
  let m = regex.exec(formattedURL);
  while (m) {
    if (m.index === regex.lastIndex) {
      regex.lastIndex += 1;
    }
    if (params[m[1]] === undefined) {
      throw new Error(`"${m[1]}" is not provided in params`);
    }
    formattedURL = formattedURL.replace(`:${m[1]}`, params[m[1]]);
    delete params[m[1]];
    m = regex.exec(formattedURL);
  }
  return formattedURL;
};

// tus upload parameters
interface UploadParams {
  url: string;
  file: File;
  progressCB?: Function;
  successCB?: Function;
  errorCB?: Function;
}

/**
 * Request with server-side rendering support
 * @param { NitroFetchRequest } url Request path
 * @param { {[key: string]: any} | FormData } opts Request parameters
 * @param { 'get' | 'post' | 'put' | 'delete' } method Request method
 * @param { 'application/x-www-form-urlencoded' | 'application/json' | 'multipart/form-data' } contentType Request content type
 * @param { {[key: string]: any} } headeropts Request header parameters
 * @param { boolean } server Whether server-side rendering is used
 * @param { Array<()=>void> } watch Watch for whether a re-request is needed
 * @returns {Promise<Response>} Request result
 */
async function requestBaseApi({
  url,
  opts = {},
  method = 'get',
  contentType = 'application/json',
  headeropts = {}
}: Params): Promise<Response> {
  const requestURL = replacePathVariables(url, opts);

  // Set up request parameters
  const params: any = {};
  if (contentType == 'application/json') {
    opts = { ...opts };
  }

  if (method == 'get') {
    params.query = opts;
  } else {
    params.body = opts;
  }

  // Network/HTTP failure flags: ofetch's retry:3 triggers the onRequestError/onResponseError
  // callbacks on every failed attempt; toasting directly inside the callbacks would pop up
  // duplicate toasts. Therefore the callbacks only record flags, and a single unified check
  // happens after the request ends (one toast).
  let networkFailed = false;
  let httpFailed = false;
  let lastStatus: number | null = null;

  // Use $fetch (not useFetch): this wrapper is only called after mount (event callbacks/composables),
  // where useFetch would trigger the NUXT_E3003 warning (cannot await in setup) and would need a
  // unique key per call to bypass the useAsyncData cache. $fetch is the underlying ofetch instance
  // used by useFetch, with identical interceptor and retry semantics, but without cache or
  // setup-timing constraints.
  // Note that $fetch throws on failure, whereas the original useFetch semantics resolve(null); to
  // preserve the caller contract of handling empty values (the outer retryFetch only retries on
  // explicit throws such as missing path parameters), exceptions are caught here and turned into
  // null; failure info is conveyed by the onResponseError flags + the unified toast.
  let data: Response | null;
  try {
    data = await $fetch<Response>(requestURL, {
      method,
      // The ofetch library auto-detects the request URL; for requests whose url already contains a
      // domain, baseURL is not prepended.
      // Fallback consistent with the streaming paths in ws.ts / bridge.ts: when VITE_API_BACK_URL is
      // not configured, fall back to the local backend address to prevent requests from degrading
      // into relative paths that hit the Nuxt dev server and return an HTML shell.
      baseURL: import.meta.env.VITE_API_BACK_URL || 'http://localhost:8080',
      ...params,
      retry: 3,
      retryDelay: 2000,
      // onRequest is equivalent to a request interceptor
      onRequest({ request, options }) {
        // Set request headers (GET requests don't need Content-Type)
        // Note: multipart/form-data must not have its Content-Type set manually, otherwise it would
        // override the boundary auto-generated by fetch/ofetch and break backend parsing
        // ("boundary is not found").
        // The correct approach is to let the browser auto-generate the Content-Type (with boundary).
        if (method !== 'get' && contentType !== 'multipart/form-data') {
          options.headers.set('Content-Type', contentType);
        }
        for (const [key, value] of Object.entries(headeropts)) {
          options.headers.set(key, value);
        }

        if (import.meta.client) {
          const token = localStorage.getItem('token');
          if (token) {
            options.headers.set('token', token);
          }
        }
      },

      onRequestError({ request, options, error }) {
        // Network-layer failure (DNS resolution failure/connection refused/offline, etc.; the request
        // never reached the server).
        // Only records the flag; the toast is shown by the unified check after the request ends
        // (this callback is entered multiple times during retry).
        networkFailed = true;
      },

      // onResponse is equivalent to a response interceptor
      onResponse({ response }) {
        // Handle response data
        // This attempt received a response (regardless of status code): reset the failure flags
        // accumulated by prior attempts.
        // Semantics: if the final attempt succeeds, the networkFailed/httpFailed flags accumulated
        // during earlier retries no longer apply, and the post-request check pops no error toast.
        networkFailed = false;
        httpFailed = false;
        if (import.meta.client) {
          // If the response contains a token, update the local token
          const token: string | null = response.headers.get('token');
          if (token) {
            localStorage.setItem('token', token);
          }

          return response;
        }
      },

      onResponseError({ request, response, options }) {
        // HTTP-level failure (4xx/5xx): record the flag and the final status code; the toast is
        // shown by the unified check after the request ends.
        // Note this callback is entered on every failed retry, and onResponse (triggered first)
        // resets the flags, so when the final attempt fails the flags still correctly end up true.
        httpFailed = true;
        lastStatus = response?.status ?? null;
      }
    });
  } catch {
    // Aligned with the original useFetch semantics: failures are not thrown to the caller; they
    // fall to null for the caller to handle as empty values.
    data = null;
  }

  // Retries exhausted and still failing → pop one global error toast (network error; or HTTP error
  // with no successful data).
  // This is the single decision point: the flags inside the callbacks never trigger a toast
  // directly, avoiding duplicate toasts from retry:3.
  if (import.meta.client && (networkFailed || (httpFailed && !data))) {
    sendRequestErrorToast(`${requestURL}${lastStatus !== null ? ` (HTTP ${lastStatus})` : ''}`);
  }

  return data as Response;
}

/**
 * Wrap a request with retries
 *
 * @param { ()=>Promise<Response> } fetchFunc Request function
 * @param { number } retryMaxCount Maximum number of retries
 * @param { number } retryDelay Delay between retries, in milliseconds
 * @returns {Promise<Response>} The response object
 */
function retryFetch(
  fetchFunc: () => Promise<Response>,
  retryMaxCount: number = 3,
  retryDelay: number = 1000
): Promise<Response> {
  return fetchFunc().catch(err => {
    if (retryMaxCount <= 0) {
      return Promise.reject(err);
    } else {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          retryFetch(fetchFunc, retryMaxCount - 1, retryDelay)
            .then(resolve)
            .catch(reject);
        }, retryDelay);
      });
    }
  });
}

/**
 * Request API
 *
 * @param { NitroFetchRequest } url Request path
 * @param { [key: string]: any | FormData } opts Request parameters
 * @param { 'get' | 'post' | 'put' | 'delete' } method Request method
 * @param { 'application/x-www-form-urlencoded' | 'application/json' | 'multipart/form-data' } contentType Request content type
 * @param { [key: string]: any } headeropts Request header parameters
 * @returns {Promise<Response>} Request result
 */
export async function fetchApi({
  url,
  opts = {},
  method = 'get',
  contentType = 'application/json',
  headeropts = {}
}: Params): Promise<Response> {
  return retryFetch(() =>
    requestBaseApi({
      url,
      opts,
      method,
      contentType,
      headeropts
    })
  );
}
