import json
import inspect
import functools
from loguru import logger
from pydantic import BaseModel, Field
from typing import Any, Callable, Sequence
from .utils import extract_and_combine_codeblocks
from langchain_core.tools import tool as create_tool
from langchain_core.language_models import BaseChatModel
from langchain_core.tools import StructuredTool, BaseTool
from langchain_core.messages import AnyMessage, SystemMessage
from langchain_core.output_parsers import PydanticOutputParser
from langgraph.graph import END, START, StateGraph, MessagesState
from langgraph.types import Command
from langgraph.typing import ContextT
from langchain.agents.middleware.types import (
    AgentMiddleware,
    ExtendedModelResponse,
    ModelRequest,
    ModelResponse,
)
from langchain_core.output_parsers import PydanticOutputParser
from langchain.agents.factory import (
    _ComposedExtendedModelResponse,
    _normalize_to_model_response,
    _build_commands,
    _chain_model_call_handlers,
    _add_middleware_edge,
    JumpTo,
)
from langgraph._internal._runnable import RunnableCallable


EvalFunction = Callable[[str, dict[str, Any]], tuple[str, dict[str, Any]]]

# ---------------------------------------------------------------------------
# Helper: build a ModelRequest for codeact
# ---------------------------------------------------------------------------
def _build_model_request(
    model: BaseChatModel,
    tools: list[BaseTool],
    prompt: str,
    state: Any,
    response_format: type[BaseModel] | None = None,
) -> ModelRequest:
    """Build a ModelRequest for the codeact agent.

    CodeAct does not use ToolStrategy / ProviderStrategy, so response_format
    is kept as a raw schema (passed through to the middleware so it *can* be
    overridden, but the codeact layer itself treats it as ``None`` for
    ``get_bound_model`` purposes --- codeact handles structured output
    entirely in its ``structured_output`` node).
    """
    return ModelRequest(
        model=model,
        messages=list(state["messages"]),
        system_message=SystemMessage(content=prompt),
        tools=tools,
        response_format=response_format,  # type: ignore[arg-type]
        state=state,
        runtime=None,
    )


# ---------------------------------------------------------------------------
# CodeActState
# ---------------------------------------------------------------------------
class CodeActState(MessagesState):
    """State schema for the CodeAct agent.

    Attributes:
        messages: Conversation message list (provided by MessagesState with add_messages reducer)
        script: Python code to execute (generated by LLM)
        context: Execution context containing available tool functions and all previous variables
        structured_response: Optional structured output (controlled by response_format)
        jump_to: Optional jump target (used by middleware)
        session_id: Current session ID, injected by build_agent_config
    """
    script: str | None
    context: dict[str, Any]
    structured_response: Any | None
    jump_to: str | None
    session_id: str | None


def _tool_signature(tool: BaseTool) -> str:
    """Extract a clean Python function signature for ``tool``.

    Priority:
      1. ``StructuredTool`` with ``tool.func`` → inspect the wrapped function directly.
      2. Any tool with ``args_schema`` (a Pydantic ``BaseModel``) → build the
         signature from model fields (preferred: handles defaults, types).
      3. Fallback to ``(*args, **kwargs)``.

    The returned signature string does **not** include the leading ``(`` / trailing ``)``
    so callers can interpolate it naturally::

        f"def {tool.name}({signature}):"
    """
    # ── Priority 1: StructuredTool with a wrapped function ──
    if isinstance(tool, StructuredTool) and tool.func is not None:
        sig = inspect.signature(tool.func)
        # Strip `self` (unlikely for @tool but present for class-bound fns)
        params = [
            p for p in sig.parameters.values()
            if p.name != "self"
        ]
        # Strip `run_manager` / `kwargs` / `callbacks` — LangChain plumbing
        hidden = {"run_manager", "kwargs", "callbacks", "tool_call_id"}
        params = [p for p in params if p.name not in hidden]
        return _format_params(params)

    # ── Priority 2: args_schema (Pydantic model) ──
    schema: BaseModel | None = getattr(tool, "args_schema", None)
    if schema is not None and isinstance(schema, type) and issubclass(schema, BaseModel):
        model_fields = getattr(schema, "model_fields", None)
        if model_fields:
            parts = []
            for fname, field in model_fields.items():
                # Build type annotation
                ann = field.annotation
                ann_str = _type_str(ann) if ann is not None else "Any"
                # Build default
                if field.is_required():
                    parts.append(f"{fname}: {ann_str}")
                else:
                    default = field.default
                    if default is None:
                        parts.append(f"{fname}: {ann_str} = None")
                    elif isinstance(default, str):
                        parts.append(f"{fname}: {ann_str} = {default!r}")
                    elif isinstance(default, (int, float, bool)):
                        parts.append(f"{fname}: {ann_str} = {default}")
                    elif default is ...:
                        parts.append(f"{fname}: {ann_str}")
                    else:
                        parts.append(f"{fname}: {ann_str} = {default}")
            return ", ".join(parts)

    # ── Priority 3: fallback ──
    return "*args, **kwargs"


def _format_params(params: list[inspect.Parameter]) -> str:
    """Format a list of ``inspect.Parameter`` into a clean signature string."""
    parts = []
    for p in params:
        # name: type
        ann = p.annotation
        ann_str = _type_str(ann) if ann is not inspect.Parameter.empty else "Any"
        default_str = ""
        if p.default is not inspect.Parameter.empty:
            if p.default is None:
                default_str = " = None"
            elif isinstance(p.default, str):
                default_str = f" = {p.default!r}"
            elif isinstance(p.default, (int, float, bool)):
                default_str = f" = {p.default}"
            else:
                default_str = f" = {p.default}"
        parts.append(f"{p.name}: {ann_str}{default_str}")
    return ", ".join(parts)


def _type_str(ann: type) -> str:
    """Convert a type annotation to a human-readable string.

    Handles common generics (``Optional[str]``, ``list[int]``, ``str | None``).
    """
    # NoneType -> "None"
    if ann is type(None):
        return "None"
    origin = getattr(ann, "__origin__", None)
    if origin is None:
        try:
            return ann.__name__
        except AttributeError:
            return str(ann)
    # GenericAlias (list[str], dict[str, int], Optional[...], Union[...])
    args = getattr(ann, "__args__", ())
    # Detect Union / Optional (both typing.Union and types.UnionType)
    _union_origin = None
    try:
        import types
        _union_origin = types.UnionType
    except Exception:
        pass
    try:
        _typing_union = getattr(__import__("typing"), "Union", None)
    except Exception:
        _typing_union = None
    _is_union = origin in (_union_origin, _typing_union)

    if _is_union:
        # Render as ``str | None`` rather than ``str, NoneType``
        elem_strs = [_type_str(a) for a in args]
        return " | ".join(elem_strs)

    # Non-union generic containers
    args_str = ", ".join(_type_str(a) for a in args)
    if origin is list:
        return f"list[{args_str}]"
    if origin is dict:
        return f"dict[{args_str}]"
    if origin is tuple:
        return f"tuple[{args_str}]"
    if origin is set:
        return f"set[{args_str}]"
    if origin is type(None):
        # Special-case: NoneType annotation -> None
        return "None"
    return str(ann)


def create_default_prompt(
    tools: list[StructuredTool],
    base_prompt: str | None = None,
    *,
    response_format: type[BaseModel] | None = None,
) -> str:
    """Create the default system prompt for the CodeAct agent."""
    tools = [t if isinstance(t, BaseTool) else create_tool(t) for t in tools]
    prompt = f"{base_prompt}\n\n" if base_prompt else ""
    prompt += """You are an agent that controls tools by writing Python code.

## CRITICAL: Output format

You MUST output EITHER:

1. A Python code snippet (in a fenced code block starting with ```python)
   that calls the available functions to accomplish the task step by step.
   Any output you want to extract from the code should be printed to the console.

2. Plain text (NO code block) if you want to ask for more information or provide the final answer.
"""

    if response_format is not None:
        pass  # structured output handled by structured_output node

    prompt += """
## ABSOLUTELY FORBIDDEN

Do NOT output tool calls in JSON format. Do NOT use <tool_call> or any JSON-based function-calling syntax.
You must use ```python code blocks to invoke tools. This is the ONLY valid way to call tools.

## Available functions

In addition to the Python Standard Library, you can use the following functions:
"""

    for tool in tools:
        sig = _tool_signature(tool)
        prompt += f"""
def {tool.name}({sig}):
    \"\"\"{tool.description}\"\"\"
    ...
"""

    prompt += """

Variables defined at the top level of previous code snippets can be referenced in your code.

Reminder: use Python code snippets to call tools"""
    return prompt


def _execute_model_sync(
    request: ModelRequest[ContextT],
    *,
    prompt: str,
    eval_fn: EvalFunction,
    tools_context: dict[str, Any],
    response_format: type[BaseModel] | None,
    name: str | None = None,
) -> ModelResponse:
    """Execute the CodeAct model step.

    This is the core model execution logic wrapped by ``wrap_model_call``
    middleware handlers.
    """
    # Build full messages: system prompt + conversation
    messages: list[AnyMessage] = []
    if request.system_message:
        messages.append(request.system_message)
    messages.extend(request.messages)

    logger.debug("[CODECT_TRACE] _execute_model_sync invoke start msgs={}", len(messages))
    output = request.model.invoke(messages)
    logger.debug("[CODECT_TRACE] _execute_model_sync invoke returned len={} has_content={}",
                len(messages), bool(output and output.content))

    if name:
        output.name = name

    # CodeAct does NOT use ToolStrategy/ProviderStrategy for structured output;
    # it extracts JSON code blocks in the ``structured_output`` graph node.
    # So ``structured_response`` is always ``None`` at this level.
    return ModelResponse(result=[output], structured_response=None)


def create_codeact(
    model: BaseChatModel,
    tools: Sequence[StructuredTool | Callable],
    eval_fn: EvalFunction,
    *,
    system_prompt: str | None = None,
    state_schema: type = CodeActState,
    response_format: type[BaseModel] | None = None,
    middleware: Sequence[AgentMiddleware] | None = None,
) -> StateGraph:
    """Create a CodeAct agent.

    In the CodeAct architecture, the LLM outputs Python code blocks which are
    executed in a sandbox, and the results are fed back to the LLM. This loop
    continues until the LLM responds with plain text (no code block).

    Args:
        model: Language model for code generation
        tools: List of tools available to the agent (plain functions or StructuredTool)
        eval_fn: Function that executes code in a sandbox.
            Signature: (code_string, locals_dict) -> (stdout_output, new_vars_dict)
        system_prompt: Optional custom system prompt (prepended to the default prompt).
            If None, the default prompt is used entirely.
        state_schema: State schema used by the agent.
        response_format: Optional Pydantic model; when provided, the LLM output is
            parsed as a structured response and stored in structured_response.
        middleware: Optional list of middleware for intercepting/augmenting agent execution.

    Returns:
        A compiled CodeAct agent (can be invoked directly)
    """
    tools = [t if isinstance(t, BaseTool) else create_tool(t) for t in tools]
    middleware = list(middleware) if middleware else []

    prompt = create_default_prompt(tools, base_prompt=system_prompt, response_format=response_format)

    # Make tool functions available in the code sandbox
    tools_context = {}
    for tool in tools:
        if isinstance(tool, StructuredTool) and tool.func is not None:
            tools_context[tool.name] = tool.func
        else:
            # Wrap tool.run so the LLM can call it with keyword arguments
            tools_context[tool.name] = functools.partial(tool.run)

    # ------------------------------------------------------------------
    # Build wrap_model_call handler chain from middleware
    # ------------------------------------------------------------------
    wrap_model_call_handlers = [
        m.wrap_model_call for m in middleware
        if hasattr(m, "wrap_model_call") and type(m).wrap_model_call is not AgentMiddleware.wrap_model_call
    ]
    composed_wrap_model_call = _chain_model_call_handlers(wrap_model_call_handlers)

    # Warn for middleware that only provides async wrap_model_call
    if not composed_wrap_model_call:
        for m in middleware:
            m_cls = type(m)
            if hasattr(m, "awrap_model_call") and m_cls.awrap_model_call is not AgentMiddleware.awrap_model_call:
                if not (hasattr(m, "wrap_model_call") and m_cls.wrap_model_call is not AgentMiddleware.wrap_model_call):
                    import warnings
                    warnings.warn(
                        f"Middleware '{m_cls.__name__}' defines awrap_model_call but CodeAct's "
                        f"graph is synchronous-only — the handler will be silently skipped."
                    )

    # ------------------------------------------------------------------
    # collect middleware-provided tools (codeact doesn't use them, but
    # we keep the interface consistent)
    # ------------------------------------------------------------------
    for mw in middleware:
        if hasattr(mw, "tools") and mw.tools:
            pass  # CodeAct does not dynamically add tools

    # ------------------------------------------------------------------
    # merge middleware state schemas into CodeActState
    # ------------------------------------------------------------------
    merged_schema: type = state_schema
    # Collect middleware schemas (TypedDicts) and merge fields into CodeActState.
    # Follows the same last-wins pattern as create_agent in factory.py.
    schemas_to_merge: list[type] = [
        mw.state_schema for mw in middleware
        if getattr(mw, "state_schema", None) is not None
        and mw.state_schema is not type(None)
    ]
    if schemas_to_merge:
        from typing import get_type_hints, Annotated
        from typing_extensions import TypedDict

        # Process middleware schemas first, then base schema last (last-wins).
        # Collect annotations; later entries override earlier ones.
        merged_annotations: dict[str, Any] = {}
        processed_schemas: list[type] = [*schemas_to_merge, state_schema]

        for schema in processed_schemas:
            try:
                hints = get_type_hints(schema, include_extras=True)
            except Exception:
                hints = {}
            merged_annotations.update(hints)

        # Apply field_info_map overrides from middleware (description-only)
        # by wrapping the annotation in Annotated[..., ...(description=...)]
        for mw in middleware:
            fim = getattr(mw, "field_info_map", None)
            if not fim:
                continue
            for field_name, overrides in fim.items():
                if field_name not in merged_annotations:
                    continue
                desc = overrides.get("description")
                if desc:
                    existing = merged_annotations[field_name]
                    merged_annotations[field_name] = Annotated[existing, Field(description=desc)]  # type: ignore[valid-type]

        merged_schema = TypedDict("CodeActState", merged_annotations)

    # Use merged_schema if any middleware schemas were found, otherwise use state_schema
    graph_state_schema: type = merged_schema if schemas_to_merge else state_schema

    # ------------------------------------------------------------------
    # Internal nodes
    # ------------------------------------------------------------------
    def call_model(state: state_schema) -> Command:
        logger.debug("[CODECT_TRACE] call_model enter msgs={}", len(state.get("messages", [])))
        # Build ModelRequest
        request = _build_model_request(
            model=model,
            tools=tools,
            prompt=prompt,
            state=state,
            response_format=response_format,
        )

        # Define the inner handler that actually executes the model
        def _inner(request: ModelRequest[ContextT]) -> ModelResponse:
            return _execute_model_sync(
                request,
                prompt=prompt,
                eval_fn=eval_fn,
                tools_context=tools_context,
                response_format=response_format,
            )

        # Execute through middleware chain or directly
        if composed_wrap_model_call is not None:
            logger.debug("[CODECT_TRACE] call_model calling composed_wrap_model_call")
            result = composed_wrap_model_call(request, _inner)
            logger.debug("[CODECT_TRACE] call_model composed_wrap_model_call returned")
            if isinstance(result, _ComposedExtendedModelResponse):
                model_response = result.model_response
                extra_commands = result.commands
            elif isinstance(result, ExtendedModelResponse):
                model_response = result.model_response
                extra_commands = [result.command] if result.command else []
            else:
                model_response = _normalize_to_model_response(result)
                extra_commands = []

            response = model_response.result[-1] if model_response.result else None
            commands_result = _build_commands(model_response, extra_commands)
            state_updates: list[dict[str, Any]] = [cmd.update for cmd in commands_result if cmd.update]
            merged_update: dict[str, Any] = {}
            for u in state_updates:
                merged_update.update(u)
        else:
            model_response = _inner(request)
            response = model_response.result[-1] if model_response.result else None
            merged_update = {"messages": model_response.result}

        if response is None or not hasattr(response, "content"):
            # Fallback: no response produced
            return Command(update={"script": None})

        content: str = response.content

        # Determine routing destinations (through after_model chain if hooks exist)
        goto_structured = after_model_first_node if hook_after_model else "structured_output"
        goto_sandbox = after_model_first_node if hook_after_model else "sandbox"

        # Extract code block → execute in sandbox
        code = extract_and_combine_codeblocks(content)
        if code:
            return Command(
                goto=goto_sandbox,
                update={"messages": [response], "script": code, **merged_update},
            )
        else:
            # No code block
            if response_format is not None:
                # response_format set → route to structured_output for formatting
                return Command(
                    goto=goto_structured,
                    update={"messages": [response], "script": None, **merged_update},
                )
            # No response_format → end loop and respond to user
            return Command(update={"messages": [response], "script": None, **merged_update})

    def structured_output(state: state_schema) -> Command:
        """Request structured JSON output via HumanMessage + json_mode + PydanticOutputParser.

        Preserves the message prefix for prefix cache hit. Uses bind(response_format)
        as an API parameter (no tool injection, no cache breakage), and
        PydanticOutputParser for post-hoc validation so parse failures can be
        handled gracefully instead of raising.
        """
        if response_format is None:
            return Command(
                update={
                    "messages": [
                        {"role": "user", "content": "Internal error: structured_output called without response_format."}
                    ],
                    "script": None,
                }
            )

        try:
            parser = PydanticOutputParser(pydantic_object=response_format)
            retry_messages = list(state["messages"]) + [
                {
                    "role": "user",
                    "content": (
                        "You must respond with a JSON object that matches "
                        "the following schema. Do NOT include any other text.\n\n"
                        f"{parser.get_format_instructions()}"
                    ),
                },
            ]
            json_mode_llm = model.bind(response_format={"type": "json_object"})
            raw_response = json_mode_llm.invoke(retry_messages)
            parsed = parser.parse(raw_response.content)
            return Command(update={"script": None, "structured_response": parsed})
        except Exception:
            pass

        return Command(update={"script": None, "structured_response": None})

    def _sanitize_for_serialization(obj: Any) -> Any:
        if hasattr(obj, "item"):
            return obj.item()
        if isinstance(obj, int) and not isinstance(obj, bool):
            # msgpack 仅支持 64-bit 有符号整数
            _MAX = 2**63 - 1
            _MIN = -(2**63)
            if obj > _MAX or obj < _MIN:
                return str(obj)
        return obj

    def sandbox(state: state_schema) -> dict:
        existing_context = state.get("context", {})
        context = {**existing_context, **tools_context}
        output, new_vars = eval_fn(state["script"], context)
        new_context = {**existing_context, **new_vars}
        new_context = {k: _sanitize_for_serialization(v) for k, v in new_context.items()}
        content = output
        return {
            "messages": [{"role": "user", "content": content}],
            "context": new_context,
        }

    # ------------------------------------------------------------------
    # Build graph and inject middleware edges
    # ------------------------------------------------------------------
    agent = StateGraph(graph_state_schema)
    agent.add_node("call_model", call_model, destinations=(END, "sandbox", "structured_output"))
    agent.add_node("sandbox", sandbox)
    agent.add_node("structured_output", structured_output, destinations=(END, "call_model"))

    # Determine if any middleware has before_agent/after_agent hooks
    # Also include middleware that only provides async hooks — inject_hooks will
    # handle the async-only case with a warning (CodeAct graph is sync-only).
    def _has_before_agent_or_async(m: AgentMiddleware) -> bool:
        return (
            _has_before_agent_hook(m)
            or (hasattr(m, "abefore_agent") and type(m).abefore_agent is not AgentMiddleware.abefore_agent)
        )

    def _has_after_agent_or_async(m: AgentMiddleware) -> bool:
        return (
            _has_after_agent_hook(m)
            or (hasattr(m, "aafter_agent") and type(m).aafter_agent is not AgentMiddleware.aafter_agent)
        )

    def _has_before_model_or_async(m: AgentMiddleware) -> bool:
        return (
            _has_before_model_hook(m)
            or (hasattr(m, "abefore_model") and type(m).abefore_model is not AgentMiddleware.abefore_model)
        )

    def _has_after_model_or_async(m: AgentMiddleware) -> bool:
        return (
            _has_after_model_hook(m)
            or (hasattr(m, "aafter_model") and type(m).aafter_model is not AgentMiddleware.aafter_model)
        )

    hook_before_agent: list[Any] = [m for m in middleware if _has_before_agent_or_async(m)]
    hook_after_agent: list[Any] = [m for m in middleware if _has_after_agent_or_async(m)]
    hook_before_model: list[Any] = [m for m in middleware if _has_before_model_or_async(m)]
    hook_after_model: list[Any] = [m for m in middleware if _has_after_model_or_async(m)]

    # Resolve routing targets for model hooks (used inside call_model closure)
    # Only consider middleware with a sync after_model hook — async-only ones
    # will be skipped by inject_hooks and their graph node won't exist.
    hook_after_model_sync: list[Any] = [m for m in middleware if _has_after_model_hook(m)]
    after_model_first_node: str | None = (
        f"{hook_after_model_sync[0].name}.after_model" if hook_after_model_sync else None
    )

    # Before/after agent hooks — only inject if at least one middleware provides them
    before_agent_first = None
    before_model_first = None
    if hook_before_agent:
        before_agent_first, _, _ = inject_hooks(
            agent,
            middleware_list=hook_before_agent,
            suffix="before_agent",
            hook_attr="before_agent",
            ahook_attr="abefore_agent",
            default_destination="call_model",
            model_destination="call_model",
            end_destination=END,
        )

    if hook_after_agent:
        inject_hooks(
            agent,
            middleware_list=hook_after_agent,
            suffix="after_agent",
            hook_attr="after_agent",
            ahook_attr="aafter_agent",
            default_destination="structured_output",  # after last model call
            model_destination="call_model",
            end_destination=END,
        )

    # Before/after model hooks
    if hook_before_model:
        before_model_first, _, _ = inject_hooks(
            agent,
            middleware_list=hook_before_model,
            suffix="before_model",
            hook_attr="before_model",
            ahook_attr="abefore_model",
            default_destination="call_model",
            model_destination="call_model",
            end_destination=END,
        )

    if hook_after_model:
        inject_hooks(
            agent,
            middleware_list=hook_after_model,
            suffix="after_model",
            hook_attr="after_model",
            ahook_attr="aafter_model",
            default_destination="sandbox",  # after model, routing to next node
            model_destination="call_model",
            end_destination=END,
        )

    # --- START edge ---
    if before_agent_first:
        agent.add_edge(START, before_agent_first)
        # Last before_agent node already edges to "call_model" via _add_middleware_edge
    elif before_model_first:
        # Route through before_model chain first (last before_model → call_model via _add_middleware_edge)
        agent.add_edge(START, before_model_first)
    else:
        agent.add_edge(START, "call_model")

    # --- sandbox → call_model loop edge ---
    # If before_model hooks exist, sandbox routes through them
    if before_model_first:
        agent.add_edge("sandbox", before_model_first)
    else:
        agent.add_edge("sandbox", "call_model")

    return agent


# ---------------------------------------------------------------------------
# Utility functions for middleware injection
# ---------------------------------------------------------------------------

def _has_before_agent_hook(mw: AgentMiddleware) -> bool:
    return (hasattr(mw, "before_agent")
            and type(mw).before_agent is not AgentMiddleware.before_agent)


def _has_after_agent_hook(mw: AgentMiddleware) -> bool:
    return (hasattr(mw, "after_agent")
            and type(mw).after_agent is not AgentMiddleware.after_agent)


def _has_before_model_hook(mw: AgentMiddleware) -> bool:
    return (hasattr(mw, "before_model")
            and type(mw).before_model is not AgentMiddleware.before_model)


def _has_after_model_hook(mw: AgentMiddleware) -> bool:
    return (hasattr(mw, "after_model")
            and type(mw).after_model is not AgentMiddleware.after_model)


def inject_hooks(
    agent: StateGraph,
    middleware_list: list[AgentMiddleware],
    suffix: str,
    hook_attr: str,
    ahook_attr: str,
    default_destination: str,
    model_destination: str,
    end_destination: str,
) -> tuple[str | None, str | None, int]:
    """Inject middleware hook nodes between other graph nodes.

    Each middleware in the list gets its own graph node named
    ``{middleware.name}.{suffix}``. Nodes are chained in order.

    Returns:
        (first_node_name, last_node_name, added_count) — the first and last
        actually-created node names, and how many nodes were added.
        Returns (None, None, 0) if no nodes were created (e.g. all async-only).
    """
    first_node_name: str | None = None
    last_node_name: str | None = None
    added_count = 0

    for i, mw in enumerate(middleware_list):
        node_name = f"{mw.name}.{suffix}"
        sync_fn = getattr(mw, hook_attr, None)
        async_fn = getattr(mw, ahook_attr, None)

        # Determine if this middleware actually defines the hook
        has_sync = sync_fn is not None and type(mw).__dict__.get(hook_attr) is not None
        has_async = async_fn is not None and type(mw).__dict__.get(ahook_attr) is not None

        if not has_sync and not has_async:
            continue

        # warn for only-async middleware: CodeAct graph is sync-only
        if not has_sync and has_async:
            import warnings
            mw_cls = type(mw).__name__
            warnings.warn(
                f"Middleware '{mw_cls}' defines async hook '{ahook_attr}' but CodeAct's "
                f"graph is synchronous-only — the hook will be silently skipped."
            )
            continue

        def make_node(fn_sync, node_name=node_name):
            def _run(state):
                result = fn_sync(state, runtime=None) if fn_sync else None
                if result is None:
                    result = {}
                if isinstance(result, dict):
                    return result
                return {}
            return _run

        agent.add_node(node_name, make_node(sync_fn, node_name))
        if first_node_name is None:
            first_node_name = node_name
        last_node_name = node_name
        added_count += 1

    # Wire edges
    prev = None
    for i, mw in enumerate(middleware_list):
        node_name = f"{mw.name}.{suffix}"
        # Skip async-only middleware that wasn't actually added as a node
        if node_name not in agent.nodes:
            continue
        if prev is None:
            # First node in chain — already added as a graph node above;
            # its incoming edge is wired by the caller (e.g. START → first before_agent node).
            pass
        else:
            agent.add_edge(prev, node_name)
        prev = node_name

    # Wire last node to the default destination
    if prev:
        _add_middleware_edge(
            agent,
            name=prev,
            default_destination=default_destination,
            model_destination=model_destination,
            end_destination=end_destination,
            can_jump_to=None,  # type: ignore[arg-type]
        )

    return first_node_name, last_node_name, added_count
