import asyncio
from pathlib import Path
from loguru import logger

from runtime import Register
from agent import codeact_agent
from langchain.tools import tool
from typing import Annotated, Any
from skills import get_skills_text
from pydantic import BaseModel, Field
from langchain_core.tools import BaseTool
from config import TEMP_DIR, WORKSPACE_DIR
from agent.codeact.core import CodeActState
from workspace import CORE_SYSTEM_FILE_NAMES
from models.LLMs.main_llm import create_main_llm
from agent.tools.subagent.type import SubAgentOutput
from langgraph.prebuilt.tool_node import InjectedState
from langchain_core.messages import HumanMessage, BaseMessage
from agent.tools.subagent.commander.tools.worker.middlewares import WorkerSummarization
from pub_func import render_template_file, slice_last_turn, sanitize_tool_use_result_pairing, build_agent_config

class WorkerStateSchema(CodeActState):
    session_id: str
    role: str

_template_dir = Path(__file__).parents[3].resolve() / "templates"

def _build_worker_prompt() -> str:
    """
    Build the worker prompt.

    Returns:
        The worker prompt string
    """

    skill_guide_text: str = f"""
    Additional notes:
    1. Replace <skill_folder> with the directory containing the SKILL.md file. For example, if the skill file is at "./skills/text_to_image/SKILL.md", the directory would be "./skills/text_to_image"
    2. Temporary resources generated by skills (e.g., images, audio) are stored in {TEMP_DIR.as_posix()}
    """
    skill_paths:str = get_skills_text(selected_skill_names = None, exclude_auth_skills=True) # Exclude high-permission skills
    skill_paths = f"{skill_paths}\n\n{skill_guide_text}"

    file_paths: list[str] = []

    # Ensure core files are always included
    for core_file in CORE_SYSTEM_FILE_NAMES:
        path = WORKSPACE_DIR / core_file
        if not path.exists():
            continue
        file_paths.append(path.read_text(encoding="utf-8"))

    parts = [skill_paths, *file_paths]

    return "\n\n".join(p for p in parts if p)


class WorkerTask(BaseModel):
    label: str = Field(description="Task label")
    description: str = Field(description="Detailed task description")
    timeout_mins: int = Field(description="Timeout duration in minutes (5-30, default 5). The task will be forcibly terminated if it exceeds this limit.", default=5, ge=5, le=30)

class WorkerArgs(BaseModel):
    worker_tasks: list[WorkerTask] = Field(description="Task list for executing logically independent, non-interfering tasks")


async def _arun_worker(
    worker_tasks: list[WorkerTask],
    master_session_id: str,
    task_id: str,
) -> list[str]:
    """Execute all tasks concurrently"""
    tasks_list: list[asyncio.Task] = []
    for t in worker_tasks:
        task: asyncio.Task = asyncio.create_task(
            _arun_task(t.label, t.description, t.timeout_mins, master_session_id, task_id)
        )
        tasks_list.append(task)

    results: tuple[Any, ...] = await asyncio.gather(*tasks_list)
    return list(results)


async def _arun_task(
    label: str,
    description: str,
    timeout_mins: int,
    session_id: str,
    task_id: str
) -> str:
    messages: list[BaseMessage] = []
    worker_session_id: str = f"worker-{session_id}-{task_id}"
    logger.info("worker [{}] start: {}, worker_session_id is {}", label, description, worker_session_id)
    try:
        timeout_seconds: int = timeout_mins * 60

        async def execute_task() -> str:
            system_prompt = (
                _build_worker_prompt()
                + "\n\n Complete the task as simply as possible, and terminate immediately upon completion to submit the results.")

            from agent.tools import build_without_session_id_tools
            from agent.middlewares import IterationBudget, HeartbeatStaleness

            # Create a fresh LLM instance for the worker on the current event loop.
            _llm = create_main_llm()

            agent = codeact_agent(
                system_prompt=system_prompt,
                model=_llm,
                tools=build_without_session_id_tools(),
                state_schema= WorkerStateSchema,
                middleware=[
                    WorkerSummarization(
                        model=_llm,
                        trigger=("messages", 30),
                        keep=("messages", 10),
                    ),
                    HeartbeatStaleness(),
                    IterationBudget()
                ],
                response_format=SubAgentOutput
            )

            agent_res: dict[str, Any] = await agent.ainvoke(
                input={"session_id": worker_session_id, "role": "worker", "messages": [HumanMessage(content=description)]},
                config=build_agent_config(session_id=worker_session_id)
            )
            structured_response: SubAgentOutput = agent_res["structured_response"]

            nonlocal messages
            messages = agent_res.get("messages", [])

            announce_content: str = render_template_file(
                file_path=(_template_dir / "subagent_announce.md").resolve().as_posix(),
                variables={
                    "label": label,
                    "status_text": "completed successfully" if structured_response.status == "ok" else "failed",
                    "task": description,
                    "finish_reason": structured_response.finish_reason,
                    "result": structured_response.result,
                }
            )

            return announce_content

        result: str = await asyncio.wait_for(execute_task(), timeout=timeout_seconds)
        return result

    except asyncio.TimeoutError:
        logger.error("Subagent [{}] timed out after {} minutes", label, timeout_mins)
        return render_template_file(
            file_path=(_template_dir / "subagent_announce.md").resolve().as_posix(),
            variables={
                "label": label,
                "status_text": "failed",
                "task": description,
                "result": f"Task timed out after {timeout_mins} minutes",
            }
        )

    except Exception as e:
        logger.exception("Subagent [{}] failed: {}", label, e)
        return render_template_file(
            file_path=(_template_dir / "subagent_announce.md").resolve().as_posix(),
            variables={
                "label": label,
                "status_text": "failed",
                "task": description,
                "result": str(e),
            }
        )

    finally:
        # clear all runtime register
        Register.clear_all_register_sessions(worker_session_id)

        if messages and len(messages) > 0:
            last_turn_messages: list[BaseMessage] = slice_last_turn(messages)["messages"]
            sanitize_tool_use_result_pairing(last_turn_messages)


def build_worker_tool() -> BaseTool:
    """Build the worker @tool with task_id closed over and error handling enabled."""
    @tool(args_schema=WorkerArgs, infer_schema=False)
    async def worker(
        worker_tasks: list[WorkerTask],
        master_session_id: Annotated[str, InjectedState("master_session_id")] = "",
        task_id: Annotated[str, InjectedState("task_id")] = "",
    ) -> list[str]:
        """Execute multiple independent sub-tasks that can run in parallel without interference. Returns a list of sub-task results."""
        return await _arun_worker(worker_tasks, master_session_id, task_id)

    worker.handle_tool_error = True
    return worker