"""Shared helpers for the skill HTTP controllers."""

import json
from pathlib import Path

from robyn import Response
from loguru import logger
from server.trigger.http.helpers import to_text_response
from server.utils.atomic_io import atomic_write_text
from config import SKILLS_STATE_FILE
from agent.tools.skill_tools.skill_manage import (
    _MAX_NAME_LENGTH,
    _VALID_NAME_RE,
)


# Canonical mapping between the on-disk top-level skill directories under
# `skills/` and the API category values exposed to clients.
#
#   disk dir    -> API category
#   ------------   ------------
#   builtin        builtin        (builtin: skills shipped with the project)
#   auto           auto           (auto: skills learned/generated by the agent)
#   plugins        third_party    (third_party: skills installed by the user/plugins)
#
# The API category string is the authoritative source consumed by the client;
# unknown directories degrade safely to third_party so they remain visible
# in the skill manager instead of disappearing.
_DISK_TO_CATEGORY = {
    "builtin": "builtin",
    "auto": "auto",
    "plugins": "third_party",
}


def _get_category(location: str) -> str:
    # location is like "./skills/<category>/<rest>/SKILL.md" — the category is
    # the second top-level path segment under the skills/ root.
    parts = location.strip("./").split("/")
    # parts[1] is the category dir (builtin/auto/plugins); parts[0] is "skills".
    if len(parts) < 2 or not parts[1]:
        return "third_party"
    return _DISK_TO_CATEGORY.get(parts[1], "third_party")


_SKIP_DIRS = {"__pycache__", ".git", ".venv", "node_modules"}
_SKIP_SUFFIXES = {".pyc", ".pyo"}


def _build_skill_file_tree(skill_root: Path):
    """Build a recursive tree of the skill directory (relative to `skill_root`).

    Each returned node is ``{"path", "name", "type", "content"}`` where ``type``
    is either ``"file"`` or ``"dir"``. Files carry their UTF-8 text content
    (``read_text`` may raise on non-text binaries; those are skipped). Files at
    the root level are sorted first, then directories, both alphabetically.
    Cache/venv noise is excluded.
    """
    nodes: list[dict] = []

    def walk(dir_path: Path, rel_prefix: str = "") -> None:
        entries = sorted(dir_path.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
        for entry in entries:
            rel = f"{rel_prefix}/{entry.name}" if rel_prefix else entry.name
            if entry.is_dir():
                if entry.name in _SKIP_DIRS:
                    continue
                nodes.append({"path": rel, "name": entry.name, "type": "dir"})
                walk(entry, rel)
            elif entry.is_file() and entry.suffix not in _SKIP_SUFFIXES:
                try:
                    text = entry.read_text(encoding="utf-8")
                except (UnicodeDecodeError, OSError):
                    logger.debug(f"Skipping non-text skill file: {entry}")
                    continue
                nodes.append({"path": rel, "name": entry.name, "type": "file", "content": text})

    walk(skill_root)
    return nodes


def _read_skills_state() -> dict[str, dict[str, bool]]:
    """Read the skills state file defensively.

    Returns a mapping of skill name -> {"active": bool}. Missing or malformed
    files degrade to an empty dict.
    """
    try:
        if not SKILLS_STATE_FILE.exists():
            return {}
        with open(SKILLS_STATE_FILE, encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            return {}
        result: dict[str, dict[str, bool]] = {}
        for key, value in data.items():
            if isinstance(value, dict) and isinstance(value.get("active"), bool):
                result[str(key)] = {"active": value["active"]}
        return result
    except (OSError, json.JSONDecodeError):
        return {}


def _write_skills_state(state: dict[str, dict[str, bool]]) -> None:
    """Write the skills state file atomically (temp file + os.replace).

    Audit 2.1.8: delegates to the shared
    :func:`server.utils.atomic_io.atomic_write_text` (temp cleanup on failure
    is handled inside the helper; the exception still propagates).
    """
    atomic_write_text(SKILLS_STATE_FILE, json.dumps(state, ensure_ascii=False, indent=4))


def _rebuild_snapshot() -> None:
    """Rebuild skills_snapshot.json after a mutation."""
    try:
        from skills.skills_snapshot import build_skills_snapshot

        build_skills_snapshot()
    except Exception:
        logger.exception("Failed to rebuild skills snapshot")


def _validate_skill_name(name: str) -> str | None:
    """Validate a skill name. Returns an error message or None if valid."""
    if not name:
        return "Skill name is required."
    if len(name) > _MAX_NAME_LENGTH:
        return f"Skill name exceeds {_MAX_NAME_LENGTH} characters."
    if not _VALID_NAME_RE.match(name):
        return (
            f"Invalid skill name '{name}'. Use lowercase letters, numbers, "
            f"hyphens, dots, and underscores. Must start with a letter or digit."
        )
    return None


def _json_response(status_code: int, payload: dict[str, object]) -> Response:
    return to_text_response(status_code, payload)
