import asyncio
from typing import Any
from pathlib import Path
from loguru import logger
from models import main_llm
from config import SESSIONS_DIR
from skills import get_skills_text
from ...type import SubAgentOutput
from pydantic import BaseModel, Field
from langchain.agents import create_agent
from langchain_core.tools import BaseTool
from config import TEMP_DIR, WORKSPACE_DIR
from workspace import CORE_SYSTEM_FILE_NAMES
from langgraph.graph.state import CompiledStateGraph
from langgraph.checkpoint.memory import InMemorySaver
from langchain_core.messages import HumanMessage, BaseMessage
from langchain.agents.middleware import SummarizationMiddleware
from pub_func import render_template_file, slice_last_turn, sanitize_tool_use_result_pairing, build_agent_config


class WorkerTask(BaseModel):
    label: str = Field(description="Task label")
    description: str = Field(description="Detailed task description")
    timeout_mins: int = Field(description="Timeout duration in minutes (5-30, default 5). The task will be forcibly terminated if it exceeds this limit.", default=5, ge=5, le=30)

class WorkerArgs(BaseModel):
    worker_tasks: list[WorkerTask] = Field(description="Task list for executing logically independent, non-interfering tasks")

class Worker(BaseTool):
    name: str = "worker"
    description: str = "Execute multiple independent sub-tasks that can run in parallel without interference. Returns a list of sub-task results."
    args_schema: type[BaseModel] | None = WorkerArgs

    _current_dir = Path(__file__).parents[2].resolve()
    _template_dir = (_current_dir / "templates").resolve()

    def __init__(self, session_id: str, task_id: str, **kwargs: Any):
        super().__init__(**kwargs)
        self._session_id: str = session_id
        self._task_id: str = task_id

        todo_dir: Path = SESSIONS_DIR / session_id / "todo"
        # Ensure the directory exists
        todo_dir.mkdir(parents=True, exist_ok=True)

        self._file_path: Path = todo_dir / f"{self._task_id}.md"

    @staticmethod
    def _build_worker_prompt() -> str:
        """
        Build the worker prompt.

        Returns:
            The worker prompt string
        """

        skill_guide_text: str = f"""
        Additional notes:
        1. Replace <skill_folder> with the directory containing the SKILL.md file. For example, if the skill file is at "./skills/text_to_image/SKILL.md", the directory would be "./skills/text_to_image"
        2. Temporary resources generated by skills (e.g., images, audio) are stored in {TEMP_DIR.as_posix()}
        """
        skill_paths:str = get_skills_text(selected_skill_names = None, exclude_auth_skills=True) # Exclude high-permission skills
        skill_paths = f"{skill_paths}\n\n{skill_guide_text}"

        file_paths: list[str] = []

        # Ensure core files are always included
        for core_file in CORE_SYSTEM_FILE_NAMES:
            path = WORKSPACE_DIR / core_file
            if not path.exists():
                continue
            file_paths.append(path.read_text(encoding="utf-8"))

        parts = [skill_paths, *file_paths]

        return "\n\n".join(p for p in parts if p)

    async def _arun_task(
        self,
        label: str,
        description: str,
        timeout_mins: int,
    ) -> str:
        messages: list[BaseMessage] = []
        try:
            # Convert minutes to seconds
            timeout_seconds: int = timeout_mins * 60

            # Define the actual task logic
            async def execute_task() -> str:
                # Build subagent system prompt
                system_prompt = (
                    self._build_worker_prompt()
                    + "\n\n Complete the task as simply as possible, and terminate immediately upon completion to submit the results.")

                from tools import MAIN_TOOLS_BUILDERS
                from agent.middlewares import ToolCallNormalize, ContextEngineHook

                agent: CompiledStateGraph = create_agent(
                    system_prompt=system_prompt,
                    model=main_llm,
                    tools=[b(self._session_id) for b in MAIN_TOOLS_BUILDERS],
                    checkpointer= InMemorySaver(),
                    middleware=[
                        ContextEngineHook(session_id=self._session_id),
                        SummarizationMiddleware(
                            model=main_llm,
                            trigger=("messages", 20),
                            keep=("messages", 10),
                        ),
                        # Must be last: abefore_model runs after Summarization to catch orphan tool_calls
                        ToolCallNormalize(self._session_id),
                    ],
                    response_format=SubAgentOutput
                )
                # Force checkpointer to False to prevent AsyncSqliteSaver default creation
                # which would bind its asyncio.Lock to the wrong event loop.
                agent.checkpointer = False
                agent_res: dict[str, Any] = await agent.ainvoke(
                    input={"messages": [HumanMessage(content=description)]},
                    config=build_agent_config(session_id=self._session_id, args=[{"recursion_limit": 50}])
                )
                structured_response: SubAgentOutput = agent_res.get("structured_response", {})

                # Get conversation history for post-task graph-memory extraction
                nonlocal messages
                messages = agent_res.get("messages", [])

                announce_content: str = render_template_file(
                    file_path=(self._template_dir / "subagent_announce.md").resolve().as_posix(),
                    variables={
                        "label": label,
                        "status_text": "completed successfully" if structured_response.status == "ok" else "failed",
                        "task": description,
                        "finish_reason": structured_response.finish_reason,
                        "result": structured_response.result,
                    }
                )

                return announce_content

            # Use asyncio.wait_for to set timeout
            result: str = await asyncio.wait_for(execute_task(), timeout=timeout_seconds)
            return result

        except asyncio.TimeoutError:
            logger.error("Subagent [%s] timed out after %s minutes", label, timeout_mins)
            return render_template_file(
                file_path=(self._template_dir / "subagent_announce.md").resolve().as_posix(),
                variables={
                    "label": label,
                    "status_text": "failed",
                    "task": description,
                    "result": f"Task timed out after {timeout_mins} minutes",
                }
            )

        except Exception as e:
            logger.error("Subagent [{}] failed: {}", label, e)
            return render_template_file(
                file_path=(self._template_dir / "subagent_announce.md").resolve().as_posix(),
                variables={
                    "label": label,
                    "status_text": "failed",
                    "task": description,
                    "result": str(e),
                }
            )

        finally:
            """Extract experience on successful task completion"""
            # Get the formatted last turn messages
            if messages and len(messages) > 0:
                last_turn_messages: list[BaseMessage] = slice_last_turn(messages)["messages"]
                format_last_turn_messages: list[BaseMessage] = sanitize_tool_use_result_pairing(last_turn_messages)


    async def _arun(
        self,
        worker_tasks: list[WorkerTask],
        **kwargs: Any
    ) -> list[str]:
        """Execute all tasks concurrently"""
        # Create all async tasks
        tasks_list: list[asyncio.Task] = []
        for t in worker_tasks:
            task: asyncio.Task = asyncio.create_task(self._arun_task(t.label, t.description, t.timeout_mins))
            tasks_list.append(task)

        # Wait for all tasks to complete and collect results
        results: tuple[Any, ...] = await asyncio.gather(*tasks_list)

        return list(results)

    def _run(
        self,
        worker_tasks: list[WorkerTask],
        **kwargs: Any
    ) -> list[str]:
        return asyncio.run(self._arun(worker_tasks, **kwargs))

def build_worker_tool(session_id: str, task_id: str) -> Worker:
    tool: Worker = Worker(session_id, task_id)
    tool.handle_tool_error = True
    return tool