from config import ROOT_DIR, SKILLS_DIR, AUTO_SKILLS_DIR

ARCHIVE_DIR = SKILLS_DIR / ".archive"
CURATOR_STATE_FILE = SKILLS_DIR / ".curator_state"
CURATOR_LOGS_DIR = ROOT_DIR / "logs" / "curator"
USAGE_DIR = AUTO_SKILLS_DIR / ".usage"
PINNED_FILE = ".pinned"

STATE_ACTIVE = "active"
STATE_STALE = "stale"
STATE_ARCHIVED = "archived"

DEFAULT_INTERVAL_HOURS = 24 * 7
DEFAULT_MIN_IDLE_HOURS = 2
DEFAULT_STALE_AFTER_DAYS = 30
DEFAULT_ARCHIVE_AFTER_DAYS = 90
DEFAULT_CONSOLIDATE = False

PROCESS_ARCHIVE = "archive"
PROCESS_DELETE = "delete"
