//! Tauri event types for real-time streaming.
//!
//! The agent uses Tauri's event system to stream responses to the
//! frontend in real time, replacing the Python backend's SSE stream.
//!
//! # Event Lifecycle
//!
//! ```text
//! agent:stream:start  ──►  agent:stream:chunk  (×N)  ──►  agent:stream:end
//!                              │
//!                              └──►  agent:stream:error  (on failure)
//! ```
//!
//! # Event Table
//!
//! | Event Name | Trigger | Payload |
//! |------------|---------|---------|
//! | `agent:stream:start` | Agent begins processing a message | [`AgentStreamStart`] |
//! | `agent:stream:chunk` | Each text fragment is generated | [`AgentStreamChunk`] |
//! | `agent:stream:end` | Agent finishes successfully | [`AgentStreamEnd`] |
//! | `agent:stream:error` | Agent encounters a failure | [`AgentStreamError`] |
//!
//! # Frontend Usage
//!
//! ```typescript
//! import { listen } from '@tauri-apps/api/event';
//!
//! // Listen for streaming chunks
//! const unlisten = await listen<AgentStreamChunk>('agent:stream:chunk', (event) => {
//!   console.log('chunk:', event.payload.content);
//! });
//!
//! // Stop listening when done
//! unlisten();
//! ```

use serde::{Deserialize, Serialize};
use ts_rs::TS;

// ── Event name constants ───────────────────────────────────

/// Emitted when the agent begins processing a user message.
pub const AGENT_STREAM_START: &str = "agent:stream:start";

/// Emitted for each text fragment generated by the agent.
pub const AGENT_STREAM_CHUNK: &str = "agent:stream:chunk";

/// Emitted when the agent finishes successfully.
pub const AGENT_STREAM_END: &str = "agent:stream:end";

/// Emitted when the agent encounters an error during processing.
pub const AGENT_STREAM_ERROR: &str = "agent:stream:error";

// ── Event payload types ─────────────────────────────────────

/// Payload for the `agent:stream:start` event.
///
/// Emitted once when the agent begins processing a user message.
///
/// | Field | Type | Description |
/// |-------|------|-------------|
/// | `session_id` | `string` | The session being processed |
/// | `message_id` | `string` | Unique ID for this message turn |
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../app/types/backend/")]
pub struct AgentStreamStart {
    /// The session being processed.
    pub session_id: String,
    /// Unique ID for this message turn (used for correlation).
    pub message_id: String,
}

/// Payload for the `agent:stream:chunk` event.
///
/// Emitted for each text fragment generated by the agent's LLM response.
///
/// | Field | Type | Description |
/// |-------|------|-------------|
/// | `session_id` | `string` | The session this chunk belongs to |
/// | `message_id` | `string` | The message turn this chunk belongs to |
/// | `content` | `string` | The text fragment |
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../app/types/backend/")]
pub struct AgentStreamChunk {
    /// The session this chunk belongs to.
    pub session_id: String,
    /// The message turn this chunk belongs to.
    pub message_id: String,
    /// The text fragment generated by the LLM.
    pub content: String,
}

/// Payload for the `agent:stream:end` event.
///
/// Emitted once when the agent finishes successfully.
///
/// | Field | Type | Description |
/// |-------|------|-------------|
/// | `session_id` | `string` | The session that completed |
/// | `message_id` | `string` | The message turn that completed |
/// | `total_chunks` | `number` | Total number of chunks emitted |
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../app/types/backend/")]
pub struct AgentStreamEnd {
    /// The session that completed.
    pub session_id: String,
    /// The message turn that completed.
    pub message_id: String,
    /// Total number of chunks emitted during this turn.
    pub total_chunks: u32,
}

/// Payload for the `agent:stream:error` event.
///
/// Emitted when the agent encounters a failure during processing.
///
/// | Field | Type | Description |
/// |-------|------|-------------|
/// | `session_id` | `string` | The session that failed |
/// | `message_id` | `string` | The message turn that failed |
/// | `code` | `string` | Machine-readable error code |
/// | `message` | `string` | Human-readable error description |
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../app/types/backend/")]
pub struct AgentStreamError {
    /// The session that failed.
    pub session_id: String,
    /// The message turn that failed.
    pub message_id: String,
    /// Machine-readable error code (e.g., `"MODEL_ERROR"`).
    pub code: String,
    /// Human-readable error description.
    pub message: String,
}

// ── Tests ───────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn event_name_constants_are_correct() {
        assert_eq!(AGENT_STREAM_START, "agent:stream:start");
        assert_eq!(AGENT_STREAM_CHUNK, "agent:stream:chunk");
        assert_eq!(AGENT_STREAM_END, "agent:stream:end");
        assert_eq!(AGENT_STREAM_ERROR, "agent:stream:error");
    }

    #[test]
    fn stream_start_serializes() {
        let payload = AgentStreamStart {
            session_id: "main".into(),
            message_id: "msg_001".into(),
        };
        let json = serde_json::to_string(&payload).unwrap();
        assert!(json.contains("\"session_id\":\"main\""));
        assert!(json.contains("\"message_id\":\"msg_001\""));
    }

    #[test]
    fn stream_chunk_serializes() {
        let payload = AgentStreamChunk {
            session_id: "main".into(),
            message_id: "msg_001".into(),
            content: "Hello!".into(),
        };
        let json = serde_json::to_string(&payload).unwrap();
        assert!(json.contains("\"content\":\"Hello!\""));
    }

    #[test]
    fn stream_end_serializes() {
        let payload = AgentStreamEnd {
            session_id: "main".into(),
            message_id: "msg_001".into(),
            total_chunks: 42,
        };
        let json = serde_json::to_string(&payload).unwrap();
        assert!(json.contains("\"total_chunks\":42"));
    }

    #[test]
    fn stream_error_serializes() {
        let payload = AgentStreamError {
            session_id: "main".into(),
            message_id: "msg_001".into(),
            code: "MODEL_ERROR".into(),
            message: "connection refused".into(),
        };
        let json = serde_json::to_string(&payload).unwrap();
        assert!(json.contains("\"code\":\"MODEL_ERROR\""));
        assert!(json.contains("\"message\":\"connection refused\""));
    }

    #[test]
    fn stream_start_round_trip() {
        let original = AgentStreamStart {
            session_id: "s1".into(),
            message_id: "m1".into(),
        };
        let json = serde_json::to_string(&original).unwrap();
        let deserialized: AgentStreamStart = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.session_id, original.session_id);
        assert_eq!(deserialized.message_id, original.message_id);
    }

    #[test]
    fn stream_chunk_round_trip() {
        let original = AgentStreamChunk {
            session_id: "s1".into(),
            message_id: "m1".into(),
            content: "Streaming text...".into(),
        };
        let json = serde_json::to_string(&original).unwrap();
        let deserialized: AgentStreamChunk = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.content, original.content);
    }

    #[test]
    fn stream_error_round_trip() {
        let original = AgentStreamError {
            session_id: "s1".into(),
            message_id: "m1".into(),
            code: "AGENT_ERROR".into(),
            message: "tool execution failed".into(),
        };
        let json = serde_json::to_string(&original).unwrap();
        let deserialized: AgentStreamError = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.code, original.code);
        assert_eq!(deserialized.message, original.message);
    }
}
