"""System prompt assembly."""

from pathlib import Path
from skills import get_skills_text
from config import WORKSPACE_DIR, TEMP_DIR
from workspace import ALL_SYSTEM_FILE_NAMES
from context_engine.xp_graph.export_skill import export_all_communities

MAX_FILE_CHARS: int = 20_000

def _read_text(path: Path) -> str:
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8")
    if len(text) > MAX_FILE_CHARS:
        return text[:MAX_FILE_CHARS] + "\n...[truncated]"
    return text


skill_guide_text: str = f"""
Notes:
1. Replace <skill_folder> with the directory containing the skill's SKILL.md file. For example, if the skill file is at "./skills/text_to_image/SKILL.md", the directory is "./skills/text_to_image".
2. Temporary resources generated by skills (e.g., images, audio) are stored in {TEMP_DIR.as_posix()}.
"""

def build_system_prompt(selected_file_names: list[str] | None = None, selected_skill_names: list[str] | None = None) -> str:
    # rebuild xp_graph skills
    export_all_communities()

    skill_paths:str = get_skills_text(selected_skill_names)
    skill_paths = f"{skill_paths}\n\n{skill_guide_text}"

    if selected_file_names is not None:
        file_paths = [_read_text(WORKSPACE_DIR / f) for f in selected_file_names]

    else:
        from agent.tools import memory_store

        file_paths = [
            *[_read_text(WORKSPACE_DIR / f) for f in ALL_SYSTEM_FILE_NAMES],
            memory_store.format_for_system_prompt("memory"),
            memory_store.format_for_system_prompt("user")
        ]

    parts = [*file_paths, skill_paths]

    return "\n\n".join(p for p in parts if p)

